### ISSUE TITLE
Option to make setting World rather than Client

### ISSUE THREAD

**Issue by steveculshaw** [mrkwnzl/free-alt-foundryvtt#1]
It'd be useful to have an option to make the setting World/Global, rather than per client.

Some of my players are luddites, so I'd like to impose the setting, rather than having to walk them through the process.

Plus one of them uses two different machines, so I know they'll forget to do the changes on both of them :-)

**Comment by mrkwnzl** [comment]
Good idea, thanks!

The just released v1.1.0 implements this.

Edit: Something is wrong with my git. I’ll push the 1.1.0 update in a few minutes again. Sorry.

**Comment by mrkwnzl** [comment]
Quick update: Something went wrong with 1.1.0. 1.1.1 should solve that.

**Comment by mrkwnzl** [comment]
All right, I was able to resolve everything. v1.1.0 is now online and should work. Sorry for the inconvenience.

**Comment by steveculshaw** [comment]
Nice one ... installed and looks good

**Comment by mrkwnzl** [comment]
Awesome! Thanks for the suggestion!
